### PR TITLE
Fix command line parsing bug

### LINKED ISSUE #64: Fix command line parsing bug
@njr2128 and @gschare (me) confirmed a bug when running `update.py` with no command line arguments, because the argparse setting defaults to `False`, while that value was erroneously being passed to `os.path.join()`, which takes strings and filepath-like objects, not Booleans.
This can be fixed by using the default value `argparse.SUPPRESS` to achieve the following logic:
- if a flag is set but not given a value by the user, use the value from `const` (i.e. the "default" value from utils.py).
- if a flag is set and given a value by the user, use that value.
- if a flag is not set, do not include it in the `args` object at all (this is what argparse.SUPPRESS does).
- before writing each derivative, check if none of the flags are set. If so, set all of them to their "default" value (which, confusingly, is also their `const` value and NOT their `default` value).
- when writing each derivative, check that it is in the `args` object. Because of the previous step, all of them should be included in the object if none of them were set, and otherwise only the ones that were set should be included.

And then for `--dry-run` logic:
- for any derivatives being written, pass the value of `args.dry_run` to the `update_...()` method. Thus, writing output to `/dev/null` is handled by each method in its own way.

It's confusing to describe but it's really nice and intuitive to actually use!

Note that this could be achieved without the use of `argparse.SUPPRESS` by simply setting default to False and checking the truthiness of the flag's value. The biggest and most important change in this aspect was that instead of simply bypassing the individual truthiness check if none of the flags were truthy, we now _modify_ `args` to use the values from `utils.py` if none of the flags were set. So it's not really a matter of "checking if flag is not set" vs "checking is flag is falsy", as both work; it just appears that defaulting to `argparse.SUPPRESS` and checking if the flag is set seems more future-proof and explicit, and also avoids a situation where a user would provide a falsy value for the flag.

### PR DESCRIPTION
**Pull request by gschare**
Fixes #64

### CODE REVIEW

**Comment by gschare** [comment]
@njr2128, you can go ahead and fetch this branch (`issue64`) and test `update.py` on your machine with Python 3.8.

**Comment by njr2128** [comment]
@tcatapano and @gschare: When trying to check out this branch and then running `python3.8 update.py`, I get the following errors:
image

**Comment by gschare** [comment]
> @tcatapano and @gschare: When trying to check out this branch and then running `python3.8 update.py`, I get the following errors:

Looks like I forgot to add this functionality to `Manuscript.update_metadata()`. Should be good now. I had to fix a larger bug from the other changes in the pull request.
I'm not loving the feeling of finding out about bugs by letting stuff break when people try to use it, so I will mock up some basic CI before we merge this one on Monday so that we can be a little more sure that it's correct.

**Comment by njr2128** [comment]
Thanks, @gschare.
Just ran it again and looks like we are good! 
image

**Comment by njr2128** [comment]
I spot-checked a few of the derivative files on my local mk-manuscript-data after running the commands in my previous comment and things look good. Namely, `entry-metadata` did not have "ge_*" or "def_*" (https://github.com/cu-mkp/m-k-manuscript-data/issues/1926) and a quick scan of 005r_2 (concave mirrors) looked well populated . I checked `allFolios/` and date stamp matched my run (in my file explorer's "last modified") so I am going to take this as successful and ready to go.

Will merge now and run for real for https://github.com/cu-mkp/m-k-manuscript-data/issues/1927

**Pull request merged**
